/**
 * Training Comparison — fetches static JSON snapshots of training metrics
 * and renders a comparison table.
 *
 * Data source: data/training-metrics/*.json (generated by scripts/export_metrics.py)
 */

const $ = (id: string): HTMLElement => document.getElementById(id)!;

const SHORT_METRICS: Record<string, string> = {
  'Train/mean_reward': 'reward',
  'Episode/rew_tracking_lin_vel': 'track_lin',
  'Episode/rew_feet_air_time': 'feet_air',
  'Episode/rew_smoothness': 'smooth',
  'Episode/rew_dof_acc': 'dof_acc',
  'Episode/rew_base_height': 'base_h',
  'Episode/rew_orientation': 'orient',
  'Episode/rew_lin_vel_z': 'lin_vel_z',
  'Episode/rew_ang_vel_xy': 'ang_vel_xy',
  'Episode/rew_collision': 'collision',
  'Episode/rew_action_rate': 'act_rate',
  'Episode/rew_stand_still': 'stand_still',
  'Episode/rew_tracking_ang_vel': 'track_ang',
};

export class TrainingComparison {
  init(): void {
    $('btn-refresh-comp').addEventListener('click', () => this.load());
    this.load();
  }

  async load(): Promise<void> {
    try {
      // Fetch index
      const indexResp = await fetch('data/training-metrics/index.json');
      if (!indexResp.ok) {
        this.showEmpty('No training data (run export_metrics.py)');
        return;
      }
      const index = await indexResp.json();
      const runs: string[] = index.runs || [];
      if (runs.length === 0) {
        this.showEmpty('No training runs found');
        return;
      }

      // Fetch latest metrics for each run (up to 8 runs)
      const comparisonData: Record<string, Record<string, number>> = {};
      const latestRuns = runs.slice(0, 8);

      await Promise.all(latestRuns.map(async (runName) => {
        try {
          const resp = await fetch(`data/training-metrics/${runName}.json`);
          if (!resp.ok) return;
          const data = await resp.json();
          comparisonData[runName] = {};
          for (const tag of Object.keys(SHORT_METRICS)) {
            if (data[tag] && data[tag].values && data[tag].values.length > 0) {
              const vals = data[tag].values;
              comparisonData[runName][tag] = vals[vals.length - 1];
            }
          }
        } catch {
          // skip failed run
        }
      }));

      if (Object.keys(comparisonData).length === 0) {
        this.showEmpty('No metrics loaded');
        return;
      }

      this.renderTable(comparisonData);
    } catch (err) {
      console.error('[TrainingComparison] Failed to load:', err);
      this.showEmpty('Failed to load training data');
    }
  }

  private renderTable(data: Record<string, Record<string, number>>): void {
    const runs = Object.keys(data);
    const thead = document.querySelector('#comp-table thead')!;
    const tbody = document.querySelector('#comp-table tbody')!;

    // Header
    thead.innerHTML =
      '<tr><th>Metric</th>' +
      runs.map((r) => `<th>${r.slice(0, 18)}</th>`).join('') +
      '</tr>';

    // Body
    tbody.innerHTML = '';
    for (const [fullName, shortName] of Object.entries(SHORT_METRICS)) {
      const tr = document.createElement('tr');
      tr.innerHTML =
        `<td>${shortName}</td>` +
        runs
          .map((r) => {
            const v = data[r]?.[fullName];
            let cls = '';
            if (v !== undefined && shortName === 'reward') {
              cls = v > 0 ? 'style="color:#4caf50"' : 'style="color:#f44336"';
            }
            return `<td ${cls}>${v !== undefined ? v.toFixed(4) : '--'}</td>`;
          })
          .join('');
      tbody.appendChild(tr);
    }
  }

  private showEmpty(msg: string): void {
    const tbody = document.querySelector('#comp-table tbody')!;
    tbody.innerHTML = `<tr><td colspan="10" style="text-align:center;color:#666;padding:8px">${msg}</td></tr>`;
  }
}
